using Xunit;
using LocalService;
using System.Net;
using System.Net.Http.Json;
namespace LocalService.Tests;
public sealed class BudgetPrivacyTests
{
    [Fact]public void Wall_clock_budget_cancels_without_checkpoint(){using var h=new Host();var s=new Store(new Settings{DataDir=h.Dir},h.Clock);var jobs=new Jobs(s,h.Clock);var j=jobs.Create(Fixtures.Job() with{Budget=new(10,1000,1000,1000)});j=jobs.Lease(j.Id,new("w",Fixtures.F,300));jobs.Command(j.Id,"start",new(j.LeaseToken!,Fixtures.F));h.Clock.Now=h.Clock.Now.AddSeconds(11);Assert.True(jobs.Get(j.Id).CancelRequested);Assert.Equal("budget-exhausted",jobs.Get(j.Id).Status);Assert.Throws<ApiError>(()=>jobs.Command(j.Id,"renew",new(j.LeaseToken!,Fixtures.F)));}
    [Fact]public void Reservation_atomic_and_conservative_recovery(){using var h=new Host();var s=new Store(new Settings{DataDir=h.Dir},h.Clock);var jobs=new Jobs(s,h.Clock);var j=jobs.Create(Fixtures.Job() with{Budget=new(100,1000,1000,20000)});j=jobs.Lease(j.Id,new("w",Fixtures.F,5));var command=new JobCommand(j.LeaseToken!,Fixtures.F);jobs.Command(j.Id,"start",command);Assert.Equal(8000,jobs.ReserveAi(j.Id,command,10,1000));Assert.Throws<ApiError>(()=>jobs.ReserveAi(j.Id,command,10,1000));h.Clock.Now=h.Clock.Now.AddSeconds(6);j=jobs.Lease(j.Id,new("w2",Fixtures.F,30));Assert.Equal(9000,j.Items.Single(x=>x.ObjectId==10).Tokens);Assert.Equal(0,j.Items.Single(x=>x.ObjectId==10).ReservedTokens);jobs.SettleAi(j.Id,10,command.LeaseToken,100);Assert.Equal(9000,jobs.Get(j.Id).Items.Single(x=>x.ObjectId==10).Tokens);}
    [Fact]public async Task Batch_prepare_needs_lease_and_budget(){await using var mock=await MockOpenAi.Start();using var h=new Host();h.Options=new Settings{DataDir=h.Dir,Key="test-key-budget",Model="test-model",Endpoint=mock.Url};using var c=h.Client();var r=await c.PostAsJsonAsync("/agent/stored-procedures/prepare",new PrepareRequest(Fixtures.Analyze(),"batch-user"));Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode);var jobs=h.Services.GetService(typeof(Jobs)) as Jobs;var j=jobs!.Create(Fixtures.Job() with{Budget=new(100,1000,1000,100)});j=jobs.Lease(j.Id,new("w",Fixtures.F,30));jobs.Command(j.Id,"start",new(j.LeaseToken!,Fixtures.F));r=await c.PostAsJsonAsync("/agent/stored-procedures/prepare",new PrepareRequest(Fixtures.Analyze(),"batch-user",j.Id,j.LeaseToken,10));Assert.Equal(HttpStatusCode.Conflict,r.StatusCode);Assert.Equal(0,mock.Calls);}
    [Theory][InlineData("SELECT 'unit-test-only' AS secret")][InlineData("SELECT '<ShowPlanXML' AS plan")][InlineData("SELECT 'Password=secret' AS connection")]
    public async Task Sensitive_sql_never_sent(string sql){await using var m=await MockOpenAi.Start();var ai=new OpenAi(new Settings{Key="unit-test-only",Model="test-model",Endpoint=m.Url},new HttpClient());Assert.Equal("sensitive_input",(await Assert.ThrowsAsync<ApiError>(()=>ai.Analyze(Fixtures.Analyze() with{SelectedSql=sql},default))).Code);Assert.Equal(0,m.Calls);}
    [Fact]public async Task Pagination(){using var h=new Host();using var c=h.Client();var s=(Store)h.Services.GetService(typeof(Store))!;for(int i=0;i<4;i++)s.Add("history",i.ToString(),new HistoryRecord(i.ToString(),h.Clock.Now,Fixtures.S,Fixtures.F,Fixtures.F,"local-rules","analyzed","not-verified"));var page=await c.GetFromJsonAsync<HistoryRecord[]>("/history?offset=1&limit=2");Assert.Equal(2,page!.Length);Assert.Equal("1",page[0].Id);Assert.Equal(HttpStatusCode.BadRequest,(await c.GetAsync("/history?limit=999")).StatusCode);}
}
