using Xunit;
using LocalService;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
namespace LocalService.Tests;
public sealed class FinalContractTests
{
    [Fact]public async Task Batch_success_settles_actual_usage(){await using var m=await MockOpenAi.Start();using var h=new Host();h.Options=new Settings{DataDir=h.Dir,Key="budget-key",Model="model",Endpoint=m.Url};using var c=h.Client();var jobs=(Jobs)h.Services.GetService(typeof(Jobs))!;var j=jobs.Create(Fixtures.Job() with{Budget=new(100,1000,10000,30000)});j=jobs.Lease(j.Id,new("w",Fixtures.F,30));jobs.Command(j.Id,"start",new(j.LeaseToken!,Fixtures.F));var r=await c.PostAsJsonAsync("/agent/stored-procedures/prepare",new PrepareRequest(Fixtures.Analyze(),"batch-user",j.Id,j.LeaseToken,10));r.EnsureSuccessStatusCode();Assert.Equal(110,jobs.Get(j.Id).Items[0].Tokens);Assert.Equal(0,jobs.Get(j.Id).Items[0].ReservedTokens);Assert.Equal(1,m.Calls);}
    [Fact]public async Task Batch_failure_conservatively_charges_reservation(){await using var m=await MockOpenAi.Start(500);using var h=new Host();h.Options=new Settings{DataDir=h.Dir,Key="budget-key",Model="model",Endpoint=m.Url};using var c=h.Client();var jobs=(Jobs)h.Services.GetService(typeof(Jobs))!;var j=jobs.Create(Fixtures.Job() with{Budget=new(100,1000,10000,30000)});j=jobs.Lease(j.Id,new("w",Fixtures.F,30));jobs.Command(j.Id,"start",new(j.LeaseToken!,Fixtures.F));var r=await c.PostAsJsonAsync("/agent/stored-procedures/prepare",new PrepareRequest(Fixtures.Analyze(),"batch-user",j.Id,j.LeaseToken,10));Assert.Equal(HttpStatusCode.BadGateway,r.StatusCode);Assert.True(jobs.Get(j.Id).Items[0].Tokens>8000);Assert.Equal(0,jobs.Get(j.Id).Items[0].ReservedTokens);}
    [Fact]public async Task Json_responses_are_size_bounded(){using var h=new Host();using var c=h.Client();var store=(Store)h.Services.GetService(typeof(Store))!;for(int i=0;i<5;i++)store.Add("history",i.ToString(),new HistoryRecord(i.ToString(),h.Clock.Now,Fixtures.S,Fixtures.F,Fixtures.S,new string('x',60000),"analyzed","not-verified"));var r=await c.GetAsync("/history");Assert.Equal(HttpStatusCode.RequestEntityTooLarge,r.StatusCode);Assert.Contains("response_too_large",await r.Content.ReadAsStringAsync());Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/history?limit=1")).StatusCode);}
    [Fact]public async Task Openapi_has_concrete_response_contracts(){using var h=new Host();using var c=h.Client();var spec=await c.GetFromJsonAsync<JsonElement>("/openapi.json");var schemas=spec.GetProperty("components").GetProperty("schemas");Assert.False(schemas.TryGetProperty("Object",out _));Assert.Contains("single-user",schemas.GetProperty("PrepareRequest").GetProperty("properties").GetProperty("trigger").GetRawText());Assert.Contains("selectedSql",schemas.GetProperty("AnalyzeRequest").GetProperty("required").GetRawText());}
}
