using Xunit;
using LocalService;
using Microsoft.Data.Sqlite;
using Microsoft.AspNetCore.Http;
using System.Net;
using System.Text.Json;
namespace LocalService.Tests;
public sealed class StorageJobsTests
{
    private static (Host,Store,Jobs) Setup(){var h=new Host();var s=new Store(new Settings{DataDir=h.Dir},h.Clock);return(h,s,new Jobs(s,h.Clock));}
    [Fact]public async Task Concurrent_sqlite_writes_and_restart(){var(h,s,_)=Setup();using(h){await Task.WhenAll(Enumerable.Range(0,40).Select(i=>Task.Run(()=>s.Add("memory",i.ToString(),new MemoryInput(Fixtures.F,Fixtures.S,"passed")))));var reopened=new Store(new Settings{DataDir=h.Dir},h.Clock);Assert.Equal(40,reopened.List<MemoryInput>("memory").Count);}}
    [Fact]public void Retention_180_days(){var(h,s,_)=Setup();using(h){s.Add("memory","old",new MemoryInput(Fixtures.F,Fixtures.S,"passed"));s.AppendAudit(new(Fixtures.F,1,Fixtures.S,Fixtures.F,"apply"));h.Clock.Now=h.Clock.Now.AddDays(181);s.Add("memory","new",new MemoryInput(Fixtures.F,Fixtures.S,"failed"));s.AppendAudit(new(Fixtures.F,2,Fixtures.S,Fixtures.F,"restore"));s.Prune(180);Assert.Single(s.List<MemoryInput>("memory"));Assert.Single(s.List<AuditRecord>("audit"));s.VerifyAudit();}}
    [Fact]public async Task Audit_parallel_hash_chain(){var(h,s,_)=Setup();using(h){await Task.WhenAll(Enumerable.Range(1,30).Select(i=>Task.Run(()=>s.AppendAudit(new(Fixtures.F,i,Fixtures.S,Fixtures.F,"apply")))));Assert.Equal(30,s.List<AuditRecord>("audit").Count);s.VerifyAudit();}}
    [Theory][InlineData("UPDATE records SET data=replace(data,'apply','reject') WHERE kind='audit'")][InlineData("DELETE FROM records WHERE kind='audit'")]
    public void Audit_tamper_detected(string sql){var(h,s,_)=Setup();using(h){s.AppendAudit(new(Fixtures.F,1,Fixtures.S,Fixtures.F,"apply"));using var c=new SqliteConnection("Pooling=False;Data Source="+Path.Combine(h.Dir,"assistant-history.db"));c.Open();using var cmd=c.CreateCommand();cmd.CommandText=sql;cmd.ExecuteNonQuery();Assert.Equal("audit_tampered",Assert.Throws<ApiError>(()=>s.VerifyAudit()).Code);Assert.Throws<ApiError>(()=>s.AppendAudit(new(Fixtures.F,2,Fixtures.S,Fixtures.F,"apply")));}}
    [Fact]public async Task Lease_only_one_winner(){var(h,_,j)=Setup();using(h){var job=j.Create(Fixtures.Job());var attempts=await Task.WhenAll(Enumerable.Range(0,10).Select(i=>Task.Run(()=>{try{j.Lease(job.Id,new("worker"+i,Fixtures.F,10));return true;}catch(ApiError){return false;}})));Assert.Single(attempts,x=>x);}}
    [Fact]public void Lease_expiry_renew_release_and_fingerprint(){var(h,s,j)=Setup();using(h){var job=j.Create(Fixtures.Job());Assert.Throws<ApiError>(()=>j.Lease(job.Id,new("worker",Fixtures.S,10)));job=j.Lease(job.Id,new("worker",Fixtures.F,10));var command=new JobCommand(job.LeaseToken!,Fixtures.F);Assert.Throws<ApiError>(()=>j.Command(job.Id,"start",command with{DatabaseFingerprint=Fixtures.S}));j.Command(job.Id,"renew",command);h.Clock.Now=h.Clock.Now.AddSeconds(61);Assert.Equal("lease_lost",Assert.Throws<ApiError>(()=>j.Command(job.Id,"start",command)).Code);var restarted=new Jobs(new Store(new Settings{DataDir=h.Dir},h.Clock),h.Clock);job=restarted.Lease(job.Id,new("worker2",Fixtures.F,10));job=restarted.Command(job.Id,"release",new(job.LeaseToken!,Fixtures.F));Assert.Null(job.LeaseToken);Assert.Equal("pending",s.Get<JobRecord>("jobs",job.Id).Status);}}
    [Fact]public void Checkpoint_idempotency_completion_and_replay(){var(h,_,j)=Setup();using(h){var job=j.Create(Fixtures.Job());job=j.Lease(job.Id,new("w",Fixtures.F,30));var cmd=new JobCommand(job.LeaseToken!,Fixtures.F);j.Command(job.Id,"start",cmd);var cp=new CheckpointRequest(cmd.LeaseToken,Fixtures.F,1,"completed",1,1,1,1);j.Checkpoint(job.Id,10,cp);j.Checkpoint(job.Id,10,cp);Assert.Throws<ApiError>(()=>j.Checkpoint(job.Id,10,cp with{Tokens=2}));Assert.Throws<ApiError>(()=>j.Command(job.Id,"complete",cmd));j.Checkpoint(job.Id,20,cp);job=j.Command(job.Id,"complete",cmd);Assert.Equal("completed",job.Status);Assert.Equal("pending",j.Replay(job.Id,false).Status);var demo=j.Replay(job.Id,true);Assert.True(demo.Demo);Assert.All(demo.Items,x=>Assert.Equal("pending",x.Status));}}
    [Fact]public void Cancel_invalidates_worker(){var(h,_,j)=Setup();using(h){var job=j.Create(Fixtures.Job());job=j.Lease(job.Id,new("w",Fixtures.F,30));var cmd=new JobCommand(job.LeaseToken!,Fixtures.F);j.Command(job.Id,"start",cmd);Assert.True(j.Cancel(job.Id).CancelRequested);Assert.Throws<ApiError>(()=>j.Checkpoint(job.Id,10,new(cmd.LeaseToken,Fixtures.F,1,"completed",1,1,1,1)));}}
    [Theory][InlineData(100001,1,1,1)][InlineData(1,1001,1,1)][InlineData(1,1,10001,1)][InlineData(1,1,1,1001)]
    public void Each_budget_exhaustion_stops_job(long elapsed,long cpu,long io,long tokens){var(h,_,j)=Setup();using(h){var job=j.Create(Fixtures.Job());job=j.Lease(job.Id,new("w",Fixtures.F,30));j.Command(job.Id,"start",new(job.LeaseToken!,Fixtures.F));job=j.Checkpoint(job.Id,10,new(job.LeaseToken!,Fixtures.F,1,"completed",elapsed,cpu,io,tokens));Assert.Equal("budget-exhausted",job.Status);Assert.True(job.CancelRequested);}}
    [Fact]public void Retry_limit(){var(h,_,j)=Setup();using(h){var job=j.Create(Fixtures.Job() with{TopN=1,ObjectIds=[10]});for(int i=1;i<=2;i++){job=j.Lease(job.Id,new("w",Fixtures.F,30));var cmd=new JobCommand(job.LeaseToken!,Fixtures.F);j.Command(job.Id,"start",cmd);j.Checkpoint(job.Id,10,new(cmd.LeaseToken,Fixtures.F,i,"failed",i,i,i,i));j.Command(job.Id,"release",cmd);if(i==1)j.Retry(job.Id);}Assert.Equal("retry_exhausted",Assert.Throws<ApiError>(()=>j.Retry(job.Id)).Code);}}
    [Fact]public void Csv_privacy_formula_escaping(){var csv=Pages.Csv(["模型"],new[]{new[]{"=cmd|'test'"}});Assert.Contains("'=cmd",csv);Assert.DoesNotContain("SELECT",csv);}
}
public sealed class SecurityTests
{
    private static DefaultHttpContext Context(){var c=new DefaultHttpContext();c.Connection.RemoteIpAddress=IPAddress.Parse("10.0.0.2");c.Request.Scheme="https";c.Request.Host=new HostString("service.example");c.Request.Headers["X-Service-Key"]="service-test-key";c.Request.Headers["X-Tenant-Id"]="tenant";c.Request.Headers["X-Device-Id"]="worker1";c.Request.Headers["X-Api-Version"]=Contract.Version;c.Request.Headers["X-Request-Id"]=Guid.NewGuid().ToString();return c;}
    private static Settings Options()=>new(){AllowRemote=true,ServiceKey="service-test-key",TenantId="tenant"};
    [Theory][InlineData("X-Service-Key")][InlineData("X-Tenant-Id")][InlineData("X-Device-Id")][InlineData("X-Api-Version")][InlineData("X-Request-Id")]
    public void Every_remote_header_required(string header){var c=Context();c.Request.Headers.Remove(header);Assert.Throws<ApiError>(()=>new SecurityGate(Options(),TimeProvider.System).Check(c));}
    [Fact]public void Https_and_optin_required(){var c=Context();Assert.Throws<ApiError>(()=>new SecurityGate(new(),TimeProvider.System).Check(c));c.Request.Scheme="http";Assert.Throws<ApiError>(()=>new SecurityGate(Options(),TimeProvider.System).Check(c));}
    [Fact]public void Per_device_limit_and_window_reset(){var clock=new TestClock();var gate=new SecurityGate(Options(),clock);var c=Context();for(int i=0;i<300;i++)gate.Check(c);Assert.Equal(429,Assert.Throws<ApiError>(()=>gate.Check(c)).Status);c.Request.Headers["X-Device-Id"]="worker2";gate.Check(c);clock.Now=clock.Now.AddMinutes(1);c.Request.Headers["X-Device-Id"]="worker1";gate.Check(c);}
}



