// Copies the woff2 chunks for Noto Sans TC (400/700), Noto Serif TC (300/600) and JetBrains Mono (400/700)
// from the installed @fontsource packages into public/fonts/, and writes
// public/fonts/fonts.css with woff2-only @font-face rules (unicode-range kept).
// Re-run with `npm run fonts` after `npm install`. Output is committed, so the deck
// works with no network at all.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'public', 'fonts')

const fonts = [
  { pkg: 'noto-sans-tc', dir: 'noto-sans-tc', css: ['400.css', '700.css'] },
  { pkg: 'noto-serif-tc', dir: 'noto-serif-tc', css: ['300.css', '600.css'] },   // Dia 風的輕字重襯線標題
  { pkg: 'jetbrains-mono', dir: 'jetbrains-mono', css: ['latin-400.css', 'latin-700.css'] },
]

let cssOut = `/* Generated by scripts/copy-fonts.mjs — do not edit by hand. */\n`
let files = 0

for (const f of fonts) {
  const src = join(root, 'node_modules', '@fontsource', f.pkg)
  const dst = join(out, f.dir)
  if (existsSync(dst)) rmSync(dst, { recursive: true })
  mkdirSync(dst, { recursive: true })
  for (const cssFile of f.css) {
    const css = readFileSync(join(src, cssFile), 'utf8')
    const rewritten = css
      // keep only the woff2 source
      .replace(/src:\s*url\(\.\/files\/([^)]+\.woff2)\) format\('woff2'\)(?:,\s*url\([^)]+\) format\('woff'\))?;/g,
        (_, name) => {
          copyFileSync(join(src, 'files', name), join(dst, name))
          files++
          return `src: url(./${f.dir}/${name}) format('woff2');`
        })
      .replace(/font-display: swap;/g, 'font-display: block;')
    cssOut += `\n/* ${f.pkg} / ${cssFile} */\n` + rewritten
  }
}

writeFileSync(join(out, 'fonts.css'), cssOut)
console.log(`fonts: copied ${files} woff2 files → public/fonts, wrote fonts.css`)
