using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace LocalService;
public static class ManagementPages
{
 public static string ScriptHash=>Convert.ToBase64String(SHA256.HashData(Encoding.UTF8.GetBytes(Script)));
 public static string Render(string section,IReadOnlyDictionary<string,decimal[]> prices)
 {
  var titles=new Dictionary<string,string>{{"history","歷史紀錄"},{"usage","用量中心"},{"governance","治理與變更稽核"}};
  var title=titles[section];
  var shell=Pages.Page(title,[],[]);
  var start=shell.IndexOf("<main>",StringComparison.Ordinal);
  return shell[..start]+"<main data-section='"+section+"'><section class='card'><label>搜尋／資料庫指紋 <input id='search' maxlength='128'></label> <label>狀態 <select id='status'><option value=''>全部</option></select></label> <label>期間 <select id='period'><option value='7'>7 天</option><option value='30'>30 天</option><option value='month'>本月</option><option value='all' selected>全部</option><option value='custom'>自訂</option></select></label><label> 從 <input id='from' type='date'></label><label> 至 <input id='to' type='date'></label><p><button id='refresh'>重新整理</button> <button id='export'>匯出目前篩選 CSV</button> <button id='deleteAll' hidden>刪除全部歷史</button></p><p id='message' role='status'></p></section><section class='card' id='summary'></section><section class='card table'><table><thead id='head'></thead><tbody id='rows'></tbody></table></section><section class='card' id='detail' hidden><h2>詳細資料</h2><pre id='detailText' style='white-space:pre-wrap;overflow-wrap:anywhere'></pre></section><section class='card' id='governance' hidden><h2>連線中唯讀排程</h2><p>排程只在 SSMS 已連線且工作區開啟時讀取摘要；關閉 SSMS 後不查詢資料庫，不自動套用。</p><label>資料庫 fingerprint <input id='database' maxlength='64'></label> <label>Top N <input id='top' type='number' min='1' max='100' value='5'></label> <label>間隔分鐘 <input id='interval' type='number' min='5' max='10080' value='30'></label> <button id='schedule'>建立排程</button> <button id='verify'>驗證稽核鏈</button></section><section class='card' id='pricing' hidden><h2>設定中的模型單價（USD / 1M tokens）</h2><p>依序為 input、cached input、cache-write、output。未設定模型不估價；歷史估價沿用呼叫時價格。</p><pre>"+WebUtility.HtmlEncode(JsonSerializer.Serialize(prices,new JsonSerializerOptions{WriteIndented=true}))+"</pre></section></main><script>"+Script+"</script></html>";
 }
 public static string Script=>RawScript.Replace("\r\n","\n");
 private const string RawScript="""
 'use strict';
 const section=document.querySelector('main').dataset.section;
 const el=id=>document.getElementById(id);
 let records=[],shown=[],headers=[];
 const message=text=>{el('message').textContent=text;};
 async function api(path,method='GET',body){const response=await fetch(path,{method,headers:{'Content-Type':'application/json','X-Api-Version':'2026-09-08'},body:body===undefined?undefined:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw Error(json.message||'服務回應失敗');return json;}
 async function all(path){let list=[];for(let offset=0;;offset+=200){const page=await api(path+'?offset='+offset+'&limit=200');if(!Array.isArray(page))throw Error('清單契約不符');list.push(...page);if(page.length<200)return list;if(list.length>=100000)throw Error('紀錄過多，請使用分頁 API 查詢');}}
 const text=v=>v===null||v===undefined?'':typeof v==='object'?JSON.stringify(v):String(v);
 const local=v=>new Date(v).toLocaleString();
 function bounds(){const p=el('period').value,now=new Date();let from=null,to=null;if(p==='custom'){from=el('from').value?new Date(el('from').value+'T00:00:00'):null;to=el('to').value?new Date(el('to').value+'T23:59:59.999'):null;}else if(p==='month')from=new Date(now.getFullYear(),now.getMonth(),1);else if(p!=='all')from=new Date(now.getTime()-Number(p)*86400000);if(from&&to&&from>to)throw Error('開始日期不可晚於結束日期');return [from,to];}
 function cells(r){if(section==='history')return [r.id,local(r.createdAt),r.databaseFingerprint,r.provider,r.status,r.verificationStatus,r.model||'未知'];if(section==='usage'){const u=r.usage;return [r.id,local(r.createdAt),u.model,u.inputTokens,u.cachedInputTokens,u.cacheWriteTokens,u.outputTokens,u.estimatedUsd??'未知',u.estimateKind??'upper-bound'];}return [r.kind,r.id,local(r.createdAt),r.databaseFingerprint,r.status];}
 function button(label,action){const b=document.createElement('button');b.textContent=label;b.addEventListener('click',()=>action().catch(e=>message(e.message)));return b;}
 function render(){const [from,to]=bounds(),query=el('search').value.trim().toLowerCase(),status=el('status').value;shown=records.filter(r=>{const d=new Date(r.createdAt);return (!from||d>=from)&&(!to||d<=to)&&(!status||r.status===status)&&(!query||cells(r).join(' ').toLowerCase().includes(query));});el('head').replaceChildren();const tr=document.createElement('tr');for(const h of [...headers,'操作']){const th=document.createElement('th');th.textContent=h;tr.append(th);}el('head').append(tr);el('rows').replaceChildren();for(const r of shown){const row=document.createElement('tr');for(const v of cells(r)){const td=document.createElement('td');td.textContent=text(v);row.append(td);}const actions=document.createElement('td');actions.append(button('詳細',async()=>{const detail=section==='history'?await api('/history/'+encodeURIComponent(r.id)):r;el('detail').hidden=false;el('detailText').textContent=JSON.stringify(detail,null,2);}));if(section==='history')actions.append(button('刪除',async()=>{if(!confirm('刪除此筆歷史？此操作無法復原。'))return;await api('/history/'+encodeURIComponent(r.id),'DELETE');await load();}));if(r.kind==='監控事件')for(const [label,state] of [['確認','acknowledged'],['解決','resolved']])actions.append(button(label,async()=>{await api('/agent/monitor/events/'+encodeURIComponent(r.id)+'/status','POST',{status:state});await load();}));row.append(actions);el('rows').append(row);}if(!shown.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=headers.length+1;td.textContent='目前沒有紀錄（符合目前篩選）';row.append(td);el('rows').append(row);}if(section==='usage'){const sum=key=>shown.reduce((s,r)=>s+Number(r.usage[key]||0),0),priced=shown.filter(r=>r.usage.estimatedUsd!==null),unknown=shown.length-priced.length;el('summary').textContent='Calls：'+shown.length+' · input：'+sum('inputTokens')+' · cached：'+sum('cachedInputTokens')+' · cache-write：'+sum('cacheWriteTokens')+' · output：'+sum('outputTokens')+' · cache hit：'+(sum('inputTokens')?100*sum('cachedInputTokens')/sum('inputTokens'):0).toFixed(1)+'% · 已知估計 USD：'+priced.reduce((s,r)=>s+Number(r.usage.estimatedUsd),0).toFixed(6)+' · 未知價格：'+unknown+' 筆';}else el('summary').textContent='符合條件：'+shown.length+' 筆';}
 async function load(){message('讀取中…');el('refresh').disabled=true;try{if(section==='history'){records=await all('/history');const usage=await all('/usage'),models=new Map(usage.map(r=>[r.id,r.usage.model]));records=records.map(r=>({...r,model:models.get(r.id)}));headers=['識別碼','本機時間','資料庫指紋','來源','狀態','驗證','模型'];}else if(section==='usage'){records=await all('/usage');headers=['識別碼','本機時間','模型','Input','Cached','Cache-write','Output','估計 USD','估價方式'];}else{records=[];for(const [path,kind] of [['/agent/memory','決策記憶'],['/agent/schedules','唯讀排程'],['/agent/monitor/events','監控事件'],['/sp/change-audit','變更稽核']]){for(const r of await all(path))records.push({...r,kind,databaseFingerprint:r.data?.databaseFingerprint??r.change?.databaseFingerprint,status:r.status??r.change?.action});}headers=['類型','識別碼','本機時間','資料庫指紋','狀態'];}records.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const selected=el('status').value;el('status').replaceChildren(new Option('全部',''));for(const state of [...new Set(records.map(r=>r.status).filter(Boolean))])el('status').append(new Option(state,state));el('status').value=selected;render();message('讀取完成');}finally{el('refresh').disabled=false;}}
 el('refresh').onclick=()=>load().catch(e=>message(e.message));for(const id of ['search','status','period','from','to'])el(id).addEventListener('input',()=>{try{render();}catch(e){message(e.message);}});
 el('export').onclick=()=>{const cell=v=>'"'+(/^[=+@\-\t\r\n]/.test(text(v))?"'":'')+text(v).replaceAll('"','""')+'"';const csv='\uFEFF'+[headers,...shown.map(cells)].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=section+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 el('deleteAll').hidden=section!=='history';el('deleteAll').onclick=async()=>{if(!confirm('刪除全部歷史（包含篩選範圍外）？此操作無法復原。'))return;try{await api('/history','DELETE');await load();}catch(e){message(e.message);}};
 el('pricing').hidden=section!=='usage';el('governance').hidden=section!=='governance';
 el('schedule').onclick=async()=>{try{const databaseFingerprint=el('database').value.trim();if(!/^[a-f0-9]{64}$/.test(databaseFingerprint))throw Error('請輸入 64 位資料庫 fingerprint');await api('/agent/schedules','POST',{databaseFingerprint,topN:Number(el('top').value),intervalMinutes:Number(el('interval').value),enabled:true});await load();}catch(e){message(e.message);}};
 el('verify').onclick=async()=>{try{const r=await api('/sp/change-audit/verify');message(r.valid?'稽核 hash-chain 有效；本機紀錄不是外部 immutable sink。':'稽核 hash-chain 驗證失敗。');}catch(e){message(e.message);}};
 load().catch(e=>message(e.message));
 """;
}
