using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Alyvo.SsmsAiSqlAssistant;
using Xunit;
public class MapTests
{
 static MapModule Module(int id,string sql=null)=>new MapModule{Id=id,Schema="dbo",Name="p"+id,Type="P",Definition=sql??"CREATE PROCEDURE dbo.p"+id+" AS SELECT 1 AS n;"};
 static ConnectionContext Context()=>new ConnectionContext{Server="localhost",Database="AlyvoSsmsAiDemo",TrustServerCertificate=true};
 [Fact]public void AllNodesReachableIncludingIndependentCyclesSharedAndViewToSp(){var graph=new MapGraph();for(int i=1;i<=12;i++)graph.Modules.Add(i,Module(i));graph.Modules[8].Type="V";foreach(var pair in new[]{(1,2),(2,3),(3,4),(5,3),(6,7),(7,6),(8,6),(1,8),(9,3)})graph.Edges.Add(new MapEdge{Caller=pair.Item1,Callee=pair.Item2});var seen=new HashSet<int>();void Visit(int id){if(!seen.Add(id))return;foreach(var e in graph.Down(id))Visit(e.Callee.Value);}foreach(var root in graph.Roots())Visit(root);Assert.Equal(graph.Modules.Keys.OrderBy(x=>x),seen.OrderBy(x=>x));Assert.Contains(10,graph.Roots());Assert.Contains(11,graph.Roots());Assert.Contains(12,graph.Roots());Assert.Equal(3,graph.IndependentCount);}
 [Fact]public void ConditionalEvidenceAndCommentSearchAreLocal(){var graph=new MapGraph();var m=Module(1,"-- 用途：每日結算\n-- Owner: Finance\nCREATE PROC dbo.p1 @x int AS IF @x=1 EXEC dbo.p2; ELSE EXEC (@x);");graph.Modules.Add(1,m);graph.Modules.Add(2,Module(2));graph.Edges.Add(new MapEdge{Caller=1,Callee=2,Schema="dbo",Entity="p2"});CallEvidence.Enrich(graph,m);Assert.Single(graph.Search("Finance"));Assert.Single(graph.Search("每日結算"));Assert.Contains(graph.Down(1),e=>e.Callee==2&&e.Line>0&&e.Condition.Contains("@x"));Assert.Contains(graph.Down(1),e=>e.Callee==null&&e.Reason.Contains("dynamic"));Assert.Empty(graph.Search("does not exist"));}
 [Fact]public void RepeatedCallSitesKeepEachConditionAndLinkedExecStaysUnresolved(){var g=new MapGraph();var m=Module(1,"CREATE PROC dbo.p1 @x int AS BEGIN IF @x=1 EXEC dbo.p2; IF @x=2 EXEC dbo.p2; EXEC ('SELECT 1') AT remote_server; END");g.Modules.Add(1,m);g.Modules.Add(2,Module(2));g.Edges.Add(new MapEdge{Caller=1,Callee=2,Schema="dbo",Entity="p2"});CallEvidence.Enrich(g,m);Assert.Equal(2,g.Down(1).Count(e=>e.Callee==2));Assert.Contains(g.Down(1),e=>e.Condition.Contains("@x=1"));Assert.Contains(g.Down(1),e=>e.Condition.Contains("@x=2"));Assert.Contains(g.Down(1),e=>e.Callee==null&&e.Server=="remote_server");}
 [Fact]public void QueryUsesExactNodeAndEscapesDatabase(){var c=Context();c.Database="db]a";var m=Module(3);var text=MapIntegration.QueryText(c,m);Assert.StartsWith("USE [db]]a];\r\nGO",text);Assert.Contains("dbo.p3",text);Assert.DoesNotContain("dbo.p1",text);m.Type="V";Assert.Throws<InvalidOperationException>(()=>MapIntegration.QueryText(c,m));}
 [Theory][InlineData("CREATE PROC dbo.p1 AS SELECT 1;")][InlineData("ALTER PROCEDURE dbo.p1 AS SELECT 1;")][InlineData("CREATE OR ALTER PROCEDURE dbo.p1 AS SELECT 1;")][InlineData("USE [AlyvoSsmsAiDemo];\nGO\nCREATE PROC dbo.p1 AS SELECT 1;\nGO")]
 public void CanonicalNormalizesDefinitionAndBatchWrapper(string sql){var a=ProcedureSource.Parse(sql,"AlyvoSsmsAiDemo");Assert.Equal(ProcedureSource.Parse("CREATE PROC dbo.p1 AS SELECT 1;","AlyvoSsmsAiDemo").Hash,a.Hash);Assert.DoesNotContain("\nGO",a.Sql);}
 [Theory][InlineData("CREATE PROC p AS SELECT 1;")][InlineData("USE master;\nGO\nCREATE PROC dbo.p AS SELECT 1;")][InlineData("CREATE PROC dbo.p WITH ENCRYPTION AS SELECT 1;")][InlineData("SELECT 1;\nGO\nCREATE PROC dbo.p AS SELECT 1;")]
 public void UnsafeDefinitionRejected(string sql)=>Assert.ThrowsAny<Exception>(()=>ProcedureSource.Parse(sql,"AlyvoSsmsAiDemo"));
 [Fact]public void VersionDedupPreservesHistoryExportAndIndependentSp(){var root=Path.Combine(Path.GetTempPath(),"AlyvoMapTests",Guid.NewGuid().ToString("N"));var repo=new VersionRepository(root);var c=Context();var m=Module(1);var v1=repo.Create(c,m,m.Definition,"initial");Assert.Equal(1,v1.Number);Assert.Equal("未套用",v1.State);Assert.Equal(1,repo.Create(c,m,"ALTER PROCEDURE dbo.p1 AS SELECT 1 AS n;","format").Number);for(int i=2;i<=12;i++)repo.Create(c,m,"CREATE PROC dbo.p1 AS SELECT "+i+" AS n;","revision "+i);var file=repo.Load(c,m);Assert.Equal(12,file.Versions.Count);Assert.Equal(13,file.NextNumber);Assert.Equal(1,file.Versions.First().Number);var export=repo.Export(c,m);Assert.Equal(12,Directory.GetFiles(export,"*.sql").Length);Assert.True(File.Exists(Path.Combine(export,"history.json")));Assert.All(file.Versions,v=>{Assert.NotEmpty(v.Author);Assert.NotEmpty(v.Diff);Assert.Equal(64,v.Hash.Length);});}
 [Fact]public async Task RealCatalogVersionApplyRestoreAndDrift()
 {
  var c=Context();var name="AlyvoMapTest_"+Guid.NewGuid().ToString("N");async Task Execute(string sql){using(var cn=c.Connect()){await cn.OpenAsync();using(var cmd=cn.CreateCommand()){cmd.CommandText=sql;await cmd.ExecuteNonQueryAsync();}}}
  await Execute("CREATE PROCEDURE dbo."+name+" AS SELECT 1 AS n;");try{var graph=await new MapCollector().Load(c,CancellationToken.None);var m=graph.Modules.Values.Single(x=>x.Name==name);Assert.Contains(m.Id,graph.Roots());Assert.Equal(0,graph.Up(m.Id));Assert.Empty(graph.Down(m.Id));var repo=new VersionRepository(Path.Combine(Path.GetTempPath(),"AlyvoMapTests",Guid.NewGuid().ToString("N")));Assert.Empty(repo.Load(c,m).Versions);var v=repo.Create(c,m,"ALTER PROCEDURE dbo."+name+" AS SELECT 2 AS n;","test candidate");await repo.Apply(c,m,v.Number,false,CancellationToken.None);var loaded=repo.Load(c,m);Assert.Single(loaded.Versions);Assert.Equal("已套用",loaded.Versions[0].State);await repo.Apply(c,m,v.Number,true,CancellationToken.None);Assert.Equal("已還原",repo.Load(c,m).Versions[0].State);await Execute("ALTER PROCEDURE dbo."+name+" AS SELECT 9 AS n;");await Assert.ThrowsAsync<InvalidOperationException>(()=>repo.Apply(c,m,v.Number,false,CancellationToken.None));var current=(await new MapCollector().Load(c,CancellationToken.None)).Modules[m.Id];Assert.Contains("SELECT 9",current.Definition);Assert.Equal(4,repo.Load(c,m).Audit.Count);}finally{await Execute("DROP PROCEDURE dbo."+name+";");}
 }
}

